### ISSUE TITLE
Integration with NetworkX Package

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/Circos#6]
Today I chatted with Aric Hagberg, the lead maintainer for NetworkX, about the possibility of integrating Circos and HivePlot with NetworkX.

Overall:
- Great interest from him.
- Comments on usability:
  - The object-oriented interface makes sense to be separate from the Graph object.
  - API is at the right level as far as he can see.
  - Will be good to get further community exposure for this to receive comments on how it can be improved.

He described a bit of his ideas w.r.t. graph drawing. There's the problem of "graph layouts", and then there's the problem of "rendering to screen". AFAIK, both CircosPlot and HivePlot implement both aspects together.

How to proceed? There are multiple possible ways. Here are some initial thoughts, and the advantages/disadvantages of each:
1. Add a `networkx` subpackage, such that the import statements look something like `from networkx.visualization import CircosPlot`.
   1. Advantages:
      1. Gain immediate name recognition for the plots.
   2. Disadvantages:
      1. Need to write good tests for the plotting package.
2. Create a `networkx-visualization` package, such that the import statements may look something like `from nxviz import CircosPlot`.
   1. Advantages:
      1. Gains name recognition for the plots.
      2. Separation of concerns - may be much easier to keep drawing separate from `networkx` codebase, which is in-line with what Aric is thinking about.
   2. Disadvantages:
      1. Few that I can think of right now.
3. Leave Circos/hiveplots as a separate package, and instead write documentation for the `networkx` package on how to use Circos/hiveplots. The import statement would look something like `from circos import CircosPlot`. 
   1. Advantages:
      1. Flexible to maintain on our own.
      2. Lowest energetic barrier to getting community recognition for the plot types.
   2. Disadvantages:
      1. No "official" `networkx` name recognition (not sure that this is important to begin with, though...)

Leaving this up here for further thoughts. @jzab, @jonchar - do you have any ideas?

**Comment by jonchar** [comment]
Cool news! Thoughts that come to mind w.r.t. each option:
1. Making a sub package a-la `networkx.visualizations` would probably create the most visibility but also maybe the most criticism (and potentially work for us, if we're up for it).
   1. Are there additional existing tools that would fit under the `nx.visualizations` aside from `CircosPlot` and `HivePlot`?
   2. Users might want some functionality similar to what's in `nx.draw` (e.g. providing graph layouts without rendering). Not immediately clear what this would take.
2. Agree. I could see this being a package for good out-of-the-box visualizations if your network lends itself to the Circos or Hive layouts. Pass it the nodes & edges and the vanilla settings get you a decent starting point that's customizable if you know matplotlib.
3. Agree. The easy option. I'd think name recognition would increase the number of users just via exposure.

I'd vote for option 2. I think it at least makes sense to consolidate Circos and Hive into an umbrella network visualization package. I don't think `networkx` is even a dependency since we just treat the nodes and edges as lists and tuples of lists (at least in Circos anyway).

**Comment by ericmjl** [comment]
I'd say option 2 is great too. 

Both CircosPlots and HivePlots have similar APIs, and I think there can be a base class that can be implemented for consolidation.

I'm going to point Aric to our thoughts here, and let's see what he thinks.

**Comment by ericmjl** [comment]
Okay! Just talked with him again this morning, he's good to go with our plan.

For now, I have setup an `nxviz` repo under my username (github.com/ericmjl/nxviz), and just added you in. There's another UW student Nelson who wants to implement a visualization for a DAG, so I've added him in as well.

**Comment by jonchar** [comment]
Sounds great, looking forward to working on this!

**Comment by ericmjl** [comment]
Cool stuff! I'm going to move discussion to the other repo, and close this one here.
